### ISSUE TITLE
Version 5 Source QuantumENDEC is having a problem with subprocess.py So, How to Fix that Thing?

### ISSUE THREAD

**Issue by iueasnick23** [ApatheticDELL/QuantumENDEC#20]
![Screenshot (25)](https://github.com/user-attachments/assets/9b3137da-2a9e-426d-aa8e-dfc36809fb2d)
So I send the alert on web interface and then, It just starting with WinError 2 on it So HELP ME PLEASE Dell ASAP! (As soon as possible!)

**Comment by iueasnick23** [comment]
See this Screenshot of the QuantumENDEC Web Interface to send alert Now I can't go through Broadcasting to the OBS because the FileNotFoundError [WinError 2] of Subprocess in Python!

**Comment by iueasnick23** [comment]
![Screenshot (27)](https://github.com/user-attachments/assets/20f1aa8a-e9b9-4ab0-9dd4-55d2c14765d3)

**Comment by ApatheticDELL** [comment]
Fix:
**QuantumENDEC is designed to be run on command prompt or PowerShell**
Typically QuantumENDEC cannot run in virtual environments as they typically do not have access to audio drivers or devices.

**Step 1**
Open command prompt and change directory to your QuantumENDEC folder.
> cd \path\to\QuantumENDEC

or

(Windows 11 exclusive): Go to QuantumENDEC folder, right-click (context menu), and select "Open terminal here"

**Step 2**
Run QuantumENDEC 

> py QuantumENDEC.py

or

> python QuantumENDEC.py


This issue is an external issue not related to QuantumENDEC, may even be user error, closing.

**Tech tip**: If you are inexperienced in advanced computer usage and python programming, should you really be spamming us with issues? We advise to go out of your way to learn more about python interpretation before making another issue on QuantumENDEC again.

**Comment by BunnyTub** [comment]
In the latest iteration of README.md...
![image](https://github.com/user-attachments/assets/fd71a7dd-78bc-44be-9dd6-332f68bd4630)
